name: simple_app
on: [push]
jobs:
    run_tests:
        environment: test environment
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '20.17.0'

            - name: Install dependencies
              run: npm install

            - name: Test GitHub Secrets and Variables
              run: |
                  echo "PORT=${{ vars.PORT }}"

            - name: Run tests
              run: npm test
    build_image:
        environment: test environment
        runs-on: ubuntu-latest
        needs: run_tests
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build Docker image
              run: |
                  docker build -t nampv1805/simple-app .
            - name: Docker login
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Push Docker image
              run: |
                  docker push nampv1805/simple-app